/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import aitbank.*;
import javax.swing.JOptionPane;


/**
 *
 * @author 5661
 */
public class ATM extends javax.swing.JFrame {

    //Temp variables to passa reference between panels
    private float tempValue = 0;
    private String tempAccount = "";
    private String tempTransaction = "";     

    //As we are not using database for this assignment I created objects of my accounts in the gui to work with them.
    private SavingsAccount savings = new SavingsAccount("Maycon Costa", 100001);
    private ChequeAccount cheque = new ChequeAccount("Maycon Costa", 200001);
    private NetSaverAccount net = new NetSaverAccount("Maycon Costa", 300001);
    private FixedAccount fixed = new FixedAccount("Maycon Costa", 400001);
    
    Account conta;
   
    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
        //Panels (Disable panels and set their visiability to false at the start)
        //Acount Panel
        accountsPanel.disable();
        accountsPanel.setVisible(false);
        //Withdraw Panel
        withdrawPanel.disable();
        withdrawPanel.setVisible(false);
        //Deposit Panel
        depositPanel.disable();
        depositPanel.setVisible(false);
        //Balance Panel
        balancePanel.disable();
        balancePanel.setVisible(false);
        setLimitButton.disable();
        setLimitButton.setVisible(false);
        //Help Panel
        helpPanel.disable();
        helpPanel.setVisible(false);
        //Continue Panel
        continuePanel.disable();
        continuePanel.setVisible(false);
        //SetLimit Panel
        setLimitPanel.disable();
        setLimitPanel.setVisible(false);
        
        //Give objects values to work with during our GUI run.
        savings.deposit(5000);
        savings.setDailyWithdrawalLimit(1000);
        cheque.deposit(3000);        
        net.deposit(1500);        
        fixed.deposit(10000);     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        balancePanel = new javax.swing.JPanel();
        backButtonB = new javax.swing.JButton();
        balanceDisplay = new javax.swing.JLabel();
        accNameDisplay = new javax.swing.JLabel();
        accNumberDisplay = new javax.swing.JLabel();
        accTypeDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        accDailyLimit = new javax.swing.JLabel();
        setLimitButton = new javax.swing.JButton();
        setLimitPanel = new javax.swing.JPanel();
        backButtonD1 = new javax.swing.JButton();
        limitTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        withdrawPanel = new javax.swing.JPanel();
        backButtonW = new javax.swing.JButton();
        amountText = new javax.swing.JTextField();
        $200Button = new javax.swing.JButton();
        $50Button = new javax.swing.JButton();
        $20Button = new javax.swing.JButton();
        $100Button = new javax.swing.JButton();
        withdrawLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountsPanel = new javax.swing.JPanel();
        fixedButton = new javax.swing.JButton();
        savingsButton = new javax.swing.JButton();
        netButton = new javax.swing.JButton();
        chequeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        depositPanel = new javax.swing.JPanel();
        backButtonD = new javax.swing.JButton();
        depositTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        continuePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        noExitButton = new javax.swing.JButton();
        yesContinueButton = new javax.swing.JButton();
        helpPanel = new javax.swing.JPanel();
        backButtonH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(570, 625));
        setResizable(false);
        getContentPane().setLayout(null);

        b0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 0F.png"))); // NOI18N
        b0.setAlignmentY(1.0F);
        b0.setBorderPainted(false);
        b0.setContentAreaFilled(false);
        b0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b0.setPreferredSize(new java.awt.Dimension(43, 34));
        b0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 0.png"))); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(200, 530, 43, 40);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 1F.png"))); // NOI18N
        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.setPreferredSize(new java.awt.Dimension(43, 33));
        b1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 1.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(150, 410, 43, 33);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 2F.png"))); // NOI18N
        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.setPreferredSize(new java.awt.Dimension(43, 33));
        b2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 2.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(200, 410, 43, 33);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 3F.png"))); // NOI18N
        b3.setAlignmentX(3.0F);
        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b3.setPreferredSize(new java.awt.Dimension(42, 33));
        b3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 3.png"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(250, 410, 41, 33);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 4.png"))); // NOI18N
        b4.setAlignmentY(0.0F);
        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.setPreferredSize(new java.awt.Dimension(43, 34));
        b4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 4F.png"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(150, 450, 43, 34);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 5.png"))); // NOI18N
        b5.setAlignmentY(0.0F);
        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.setPreferredSize(new java.awt.Dimension(43, 34));
        b5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 5F.png"))); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(200, 450, 43, 34);

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 6F.png"))); // NOI18N
        b6.setAlignmentX(3.0F);
        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b6.setPreferredSize(new java.awt.Dimension(42, 34));
        b6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 6.png"))); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(250, 450, 41, 34);

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 7F.png"))); // NOI18N
        b7.setAlignmentY(1.0F);
        b7.setBorderPainted(false);
        b7.setContentAreaFilled(false);
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.setPreferredSize(new java.awt.Dimension(43, 36));
        b7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 7.png"))); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(150, 490, 43, 36);

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 8F.png"))); // NOI18N
        b8.setAlignmentY(1.0F);
        b8.setBorderPainted(false);
        b8.setContentAreaFilled(false);
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.setPreferredSize(new java.awt.Dimension(43, 36));
        b8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 8.png"))); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(200, 490, 43, 36);

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 9F.png"))); // NOI18N
        b9.setAlignmentY(1.0F);
        b9.setBorderPainted(false);
        b9.setContentAreaFilled(false);
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.setPreferredSize(new java.awt.Dimension(41, 36));
        b9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 9.png"))); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(250, 490, 41, 36);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset Cancel.png"))); // NOI18N
        cancelButton.setBorderPainted(false);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setPreferredSize(new java.awt.Dimension(85, 34));
        cancelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset CancelR.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(325, 410, 85, 34);

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset Clear.png"))); // NOI18N
        clearButton.setBorderPainted(false);
        clearButton.setContentAreaFilled(false);
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.setPreferredSize(new java.awt.Dimension(85, 35));
        clearButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset ClearR.png"))); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(325, 450, 85, 35);

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset Enter.png"))); // NOI18N
        enterButton.setBorderPainted(false);
        enterButton.setContentAreaFilled(false);
        enterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterButton.setPreferredSize(new java.awt.Dimension(85, 35));
        enterButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset EnterR.png"))); // NOI18N
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton);
        enterButton.setBounds(325, 530, 85, 40);

        mainPanel.setBackground(new java.awt.Color(233, 236, 242));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(233, 236, 242));
        homePanel.setPreferredSize(new java.awt.Dimension(100, 105));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/help.png"))); // NOI18N
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/helpR.png"))); // NOI18N
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        homePanel.add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 150, 40));

        balanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/balance.png"))); // NOI18N
        balanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balanceButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/balanceR.png"))); // NOI18N
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        homePanel.add(balanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));

        depositButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/deposit.png"))); // NOI18N
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/depositR.png"))); // NOI18N
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        homePanel.add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, 40));

        withdrawButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/withdraw.png"))); // NOI18N
        withdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/withdrawR2.png"))); // NOI18N
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        homePanel.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 40));

        mainPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        balancePanel.setBackground(new java.awt.Color(233, 236, 242));
        balancePanel.setEnabled(false);
        balancePanel.setPreferredSize(new java.awt.Dimension(100, 105));

        backButtonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        backButtonB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtonB.setPreferredSize(new java.awt.Dimension(100, 25));
        backButtonB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 59.png"))); // NOI18N
        backButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonBActionPerformed(evt);
            }
        });

        balanceDisplay.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        balanceDisplay.setForeground(new java.awt.Color(42, 129, 188));
        balanceDisplay.setText("$");

        accNameDisplay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accNameDisplay.setForeground(new java.awt.Color(42, 129, 188));
        accNameDisplay.setText("Account name:");

        accNumberDisplay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accNumberDisplay.setForeground(new java.awt.Color(42, 129, 188));
        accNumberDisplay.setText("Account number:");

        accTypeDisplay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accTypeDisplay.setForeground(new java.awt.Color(42, 129, 188));
        accTypeDisplay.setText("Account type:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 82, 137));
        jLabel7.setText("Balance:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 129, 188));
        jLabel8.setText("$");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 82, 137));
        jLabel9.setText("Account name:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 82, 137));
        jLabel10.setText("Account number:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 82, 137));
        jLabel11.setText("Account type:");

        jTextField1.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(26, 82, 137));
        jLabel12.setText("Daily withdraw limit:");

        accDailyLimit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accDailyLimit.setForeground(new java.awt.Color(42, 129, 188));
        accDailyLimit.setText("Limit");

        setLimitButton.setBackground(new java.awt.Color(26, 82, 137));
        setLimitButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setLimitButton.setForeground(new java.awt.Color(255, 255, 255));
        setLimitButton.setText("Set daily withdraw limit.");
        setLimitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLimitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLimitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balancePanelLayout = new javax.swing.GroupLayout(balancePanel);
        balancePanel.setLayout(balancePanelLayout);
        balancePanelLayout.setHorizontalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(balancePanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(balanceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(balancePanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(7, 7, 7)
                                .addComponent(accNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(balancePanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(5, 5, 5)
                                .addComponent(accTypeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accNumberDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(balancePanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accDailyLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(balancePanelLayout.createSequentialGroup()
                                .addComponent(backButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setLimitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addGap(42, 42, 42))
        );
        balancePanelLayout.setVerticalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(accNameDisplay))
                .addGap(9, 9, 9)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(accNumberDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(accTypeDisplay))
                .addGap(9, 9, 9)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(accDailyLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setLimitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        mainPanel.add(balancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        setLimitPanel.setBackground(new java.awt.Color(233, 236, 242));
        setLimitPanel.setEnabled(false);
        setLimitPanel.setPreferredSize(new java.awt.Dimension(100, 105));
        setLimitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtonD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        backButtonD1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtonD1.setPreferredSize(new java.awt.Dimension(100, 25));
        backButtonD1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 59.png"))); // NOI18N
        backButtonD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonD1ActionPerformed(evt);
            }
        });
        setLimitPanel.add(backButtonD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        limitTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limitTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        limitTextField.setToolTipText("");
        setLimitPanel.add(limitTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 82, 137));
        jLabel5.setText("Please, enter new daily withdraw limit.");
        setLimitPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        mainPanel.add(setLimitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        withdrawPanel.setBackground(new java.awt.Color(233, 236, 242));
        withdrawPanel.setEnabled(false);
        withdrawPanel.setPreferredSize(new java.awt.Dimension(100, 105));
        withdrawPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        backButtonW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtonW.setPreferredSize(new java.awt.Dimension(100, 25));
        backButtonW.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 59.png"))); // NOI18N
        backButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonWActionPerformed(evt);
            }
        });
        withdrawPanel.add(backButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        amountText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amountText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        withdrawPanel.add(amountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, 40));

        $200Button.setBackground(new java.awt.Color(26, 82, 137));
        $200Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        $200Button.setForeground(new java.awt.Color(255, 255, 255));
        $200Button.setText("$ 200");
        $200Button.setBorder(null);
        $200Button.setBorderPainted(false);
        $200Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        $200Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $200ButtonActionPerformed(evt);
            }
        });
        withdrawPanel.add($200Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 40));

        $50Button.setBackground(new java.awt.Color(26, 82, 137));
        $50Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        $50Button.setForeground(new java.awt.Color(255, 255, 255));
        $50Button.setText("$ 50");
        $50Button.setBorder(null);
        $50Button.setBorderPainted(false);
        $50Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        $50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $50ButtonActionPerformed(evt);
            }
        });
        withdrawPanel.add($50Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        $20Button.setBackground(new java.awt.Color(26, 82, 137));
        $20Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        $20Button.setForeground(new java.awt.Color(255, 255, 255));
        $20Button.setText("$ 20");
        $20Button.setBorder(null);
        $20Button.setBorderPainted(false);
        $20Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        $20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $20ButtonActionPerformed(evt);
            }
        });
        withdrawPanel.add($20Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 40));

        $100Button.setBackground(new java.awt.Color(26, 82, 137));
        $100Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        $100Button.setForeground(new java.awt.Color(255, 255, 255));
        $100Button.setText("$ 100");
        $100Button.setBorder(null);
        $100Button.setBorderPainted(false);
        $100Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        $100Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $100ButtonActionPerformed(evt);
            }
        });
        withdrawPanel.add($100Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 40));

        withdrawLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        withdrawLabel.setForeground(new java.awt.Color(26, 82, 137));
        withdrawLabel.setText("Please choose amount.");
        withdrawPanel.add(withdrawLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 82, 137));
        jLabel1.setText("Other:");
        withdrawPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        mainPanel.add(withdrawPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        accountsPanel.setBackground(new java.awt.Color(233, 236, 242));
        accountsPanel.setEnabled(false);
        accountsPanel.setPreferredSize(new java.awt.Dimension(100, 105));
        accountsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fixedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/fixed.png"))); // NOI18N
        fixedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fixedButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/fixedR.png"))); // NOI18N
        fixedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedButtonActionPerformed(evt);
            }
        });
        accountsPanel.add(fixedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 150, 40));

        savingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/saving.png"))); // NOI18N
        savingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savingsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/savingR.png"))); // NOI18N
        savingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsButtonActionPerformed(evt);
            }
        });
        accountsPanel.add(savingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 40));

        netButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/net.png"))); // NOI18N
        netButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        netButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/netR.png"))); // NOI18N
        netButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netButtonActionPerformed(evt);
            }
        });
        accountsPanel.add(netButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));

        chequeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/cheque.png"))); // NOI18N
        chequeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chequeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/chequeR.png"))); // NOI18N
        chequeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeButtonActionPerformed(evt);
            }
        });
        accountsPanel.add(chequeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 150, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 82, 137));
        jLabel4.setText("Select Account");
        accountsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        mainPanel.add(accountsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        depositPanel.setBackground(new java.awt.Color(233, 236, 242));
        depositPanel.setEnabled(false);
        depositPanel.setPreferredSize(new java.awt.Dimension(100, 105));
        depositPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtonD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        backButtonD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtonD.setPreferredSize(new java.awt.Dimension(100, 25));
        backButtonD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 59.png"))); // NOI18N
        backButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonDActionPerformed(evt);
            }
        });
        depositPanel.add(backButtonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        depositTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        depositTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depositTextField.setToolTipText("");
        depositPanel.add(depositTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 82, 137));
        jLabel2.setText("Please, enter amount for deposit.");
        depositPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        mainPanel.add(depositPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        continuePanel.setBackground(new java.awt.Color(233, 236, 242));
        continuePanel.setEnabled(false);
        continuePanel.setPreferredSize(new java.awt.Dimension(100, 105));
        continuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 82, 137));
        jLabel3.setText("Would you like to make another transaction?");
        continuePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        noExitButton.setBackground(new java.awt.Color(26, 82, 137));
        noExitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        noExitButton.setForeground(new java.awt.Color(255, 255, 255));
        noExitButton.setText("NO, exit!");
        noExitButton.setBorder(null);
        noExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noExitButtonActionPerformed(evt);
            }
        });
        continuePanel.add(noExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 130, 40));

        yesContinueButton.setBackground(new java.awt.Color(26, 82, 137));
        yesContinueButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        yesContinueButton.setForeground(new java.awt.Color(255, 255, 255));
        yesContinueButton.setText("YES, continue!");
        yesContinueButton.setBorder(null);
        yesContinueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yesContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesContinueButtonActionPerformed(evt);
            }
        });
        continuePanel.add(yesContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        mainPanel.add(continuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        helpPanel.setBackground(new java.awt.Color(233, 236, 242));
        helpPanel.setEnabled(false);
        helpPanel.setPreferredSize(new java.awt.Dimension(100, 105));
        helpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButtonH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/back.png"))); // NOI18N
        backButtonH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtonH.setPreferredSize(new java.awt.Dimension(100, 25));
        backButtonH.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Asset 59.png"))); // NOI18N
        backButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonHActionPerformed(evt);
            }
        });
        helpPanel.add(backButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(233, 236, 242));
        jScrollPane1.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(233, 236, 242));
        jTextPane1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ullamcorper magna ac nunc interdum iaculis. Mauris eget fermentum est. Cras tincidunt facilisis nisi, eu cursus nunc sagittis eget. Integer laoreet ut nibh a congue. Mauris pellentesque augue quis purus egestas tempor. Etiam vehicula arcu quis diam volutpat consequat.");
        jScrollPane1.setViewportView(jTextPane1);

        helpPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 130));

        mainPanel.add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 200));

        getContentPane().add(mainPanel);
        mainPanel.setBounds(70, 70, 420, 200);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Atm2.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 570, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Checks what kind of transaction if currently being done and implements it and calls its panel.
    public void transaction(Account account){
        //Withdraw
        if(this.tempTransaction.equals("withdraw")){      
            if(this.tempValue <= 0){
                JOptionPane.showMessageDialog(null, "Sorry, withdrawal should be greater than 0.");
                amountText.setText("");
                accountsPanel.disable();
                accountsPanel.setVisible(false);
                withdrawPanel.enable();
                withdrawPanel.setVisible(true);
            }
            else if(account.withdraw(this.tempValue) == 0){
                this.tempValue = 0;
                this.tempTransaction = "";
                amountText.setText("");
                accountsPanel.disable();
                accountsPanel.setVisible(false);
                continuePanel.enable();
                continuePanel.setVisible(true);
                
            }
            else{
                amountText.setText("");
                accountsPanel.disable();
                accountsPanel.setVisible(false);
                withdrawPanel.enable();
                withdrawPanel.setVisible(true);
            }
        } 
        //Deposit
        else if(this.tempTransaction.equals("deposit")){
            //check if 0 or negative value
            if(this.tempValue <= 0){
                JOptionPane.showMessageDialog(null, "Sorry, deposit should be greater than 0.");
                depositTextField.setText("");
                accountsPanel.disable();
                accountsPanel.setVisible(false);
                depositPanel.enable();
                depositPanel.setVisible(true);
            }
            else{
                account.deposit(this.tempValue);                
                JOptionPane.showMessageDialog(null, "Deposit successful done!");
                this.tempValue = 0;
                this.tempTransaction = "";
                depositTextField.setText("");
                accountsPanel.disable();
                accountsPanel.setVisible(false);
                continuePanel.enable();
                continuePanel.setVisible(true);
                
            }
        }
        //Balance
        else{
            balanceDisplay.setText(Float.toString(account.getAccBalance()));
            accNameDisplay.setText(account.getAccName());
            accNumberDisplay.setText(Integer.toString(account.getAccNumber()));            
            if(tempAccount.equals("savings")){
                setLimitButton.enable();
                setLimitButton.setVisible(true);
                accTypeDisplay.setText("Savings");  
                accDailyLimit.setText("$"+savings.getDailyWithdrawLimit());
            }else if(tempAccount.equals("cheque")){
                accTypeDisplay.setText("Cheque");
                accDailyLimit.setText("none");
            }else if(tempAccount.equals("net")){
                accTypeDisplay.setText("Net-Saver");
                accDailyLimit.setText("$"+net.getDailyWithdrawalLimit());
            }else{
                accTypeDisplay.setText("Fixed");
                accDailyLimit.setText("none");
            }
            accountsPanel.disable();
            accountsPanel.setVisible(false);
            balancePanel.enable();
            balancePanel.setVisible(true);
            
        }
    }
    
    //Withdraw button
    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        homePanel.disable();
        homePanel.setVisible(false);
        withdrawPanel.enable();
        withdrawPanel.setVisible(true);
        tempTransaction = "withdraw";    
    }//GEN-LAST:event_withdrawButtonActionPerformed

       
    //Back button(withdraw panel)
    private void backButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonWActionPerformed
        withdrawPanel.disable();
        withdrawPanel.setVisible(false);
        homePanel.enable();
        homePanel.setVisible(true);
        tempTransaction = "";
        amountText.setText("");
        depositTextField.setText("");
    }//GEN-LAST:event_backButtonWActionPerformed

    //Clear button
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //Clear in the withdraw screen
        if(withdrawPanel.isEnabled())
        {
            amountText.setText("");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText("");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText("");
        }
    }//GEN-LAST:event_clearButtonActionPerformed
    //Enter button
    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        if(!homePanel.isEnabled()){
                if(withdrawPanel.isEnabled()){
                    try{
                        tempValue = Float.parseFloat(amountText.getText());                        
                        withdrawPanel.disable();
                        withdrawPanel.setVisible(false);                    
                        accountsPanel.enable();
                        accountsPanel.setVisible(true);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(null, "Please, enter a valid withdraw value.");
                        amountText.setText("");
                    }
                }
                else if(depositPanel.isEnabled()){
                    try{
                        tempValue = Float.parseFloat(depositTextField.getText());
                        depositPanel.disable();
                        depositPanel.setVisible(false);
                        accountsPanel.enable();
                        accountsPanel.setVisible(true);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(null, "Please, enter a valid deposit value.");
                        depositTextField.setText("");
                    }                                      
                }
                else if(setLimitPanel.isEnabled()){
                    try {
                            if(Float.parseFloat(limitTextField.getText())>0){
                                savings.setDailyWithdrawalLimit(Float.parseFloat(limitTextField.getText()));
                                JOptionPane.showMessageDialog(null, "New daily withdraw limit aplied.");
                                transaction(savings);//Updates balance panel data
                                setLimitPanel.disable();
                                setLimitPanel.setVisible(false);
                                balancePanel.enable();
                                balancePanel.setVisible(true);
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Daily withdraw limit should be greater than 0.");
                            }
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "Please, enter a valid limit value.");
                    }
                    limitTextField.setText("");
                }
                
        }
        
    }//GEN-LAST:event_enterButtonActionPerformed

    //back to home from deposit
    private void backButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonDActionPerformed
        depositPanel.disable();
        depositPanel.setVisible(false);
        homePanel.enable();
        homePanel.setVisible(true);
        tempTransaction = "";
        amountText.setText("");
        depositTextField.setText("");
    }//GEN-LAST:event_backButtonDActionPerformed

    //back to home from balance
    private void backButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonBActionPerformed
        balancePanel.disable();
        balancePanel.setVisible(false);
        homePanel.enable();
        homePanel.setVisible(true);
        tempTransaction = "";
        amountText.setText("");
        depositTextField.setText("");
        setLimitButton.disable();
        setLimitButton.setVisible(false);
    }//GEN-LAST:event_backButtonBActionPerformed

    //back to home from help
    private void backButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonHActionPerformed
        helpPanel.disable();
        helpPanel.setVisible(false);
        homePanel.enable();
        homePanel.setVisible(true);
        amountText.setText("");
        depositTextField.setText("");
    }//GEN-LAST:event_backButtonHActionPerformed

    //Deposit button
    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        homePanel.disable();
        homePanel.setVisible(false);
        depositPanel.enable();
        depositPanel.setVisible(true);
        tempTransaction = "deposit";
    }//GEN-LAST:event_depositButtonActionPerformed

    //Balance button
    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        homePanel.disable();
        homePanel.setVisible(false);
        accountsPanel.enable();
        accountsPanel.setVisible(true);
        tempTransaction = "balance";
    }//GEN-LAST:event_balanceButtonActionPerformed

    //Help button
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        homePanel.disable();
        homePanel.setVisible(false);
        helpPanel.enable();
        helpPanel.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    //$20 button
    private void $200ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$200ButtonActionPerformed
        amountText.setText("200");
    }//GEN-LAST:event_$200ButtonActionPerformed
    //$50 buttom
    private void $50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$50ButtonActionPerformed
        amountText.setText("50");
    }//GEN-LAST:event_$50ButtonActionPerformed
    //$100 button
    private void $20ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$20ButtonActionPerformed
        amountText.setText("20");
    }//GEN-LAST:event_$20ButtonActionPerformed
    //$200 button
    private void $100ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$100ButtonActionPerformed
        amountText.setText("100");
    }//GEN-LAST:event_$100ButtonActionPerformed

    //NUMPAD
    //number 1 button
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"1");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"1");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"1");
        }
    }//GEN-LAST:event_b1ActionPerformed
    //number 2 button
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"2");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"2");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"2");
        }
    }//GEN-LAST:event_b2ActionPerformed
    //number 3  button
    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"3");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"3");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"3");
        }
    }//GEN-LAST:event_b3ActionPerformed
    //number 4 button
    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"4");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"4");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"4");
        }
    }//GEN-LAST:event_b4ActionPerformed
    //number 5 button
    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"5");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"5");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"5");
        }
    }//GEN-LAST:event_b5ActionPerformed
    //number 6 button
    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"6");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"6");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"6");
        }
    }//GEN-LAST:event_b6ActionPerformed
    //number 7 button
    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"7");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"7");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"7");
        }
    }//GEN-LAST:event_b7ActionPerformed
    //number 8 button
    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"8");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"8");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"8");
        }
    }//GEN-LAST:event_b8ActionPerformed
    //number 9 button
    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"9");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"9");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"9");
        }
    }//GEN-LAST:event_b9ActionPerformed
    //number 0 button
    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(withdrawPanel.isEnabled()){
            amountText.setText(amountText.getText()+"0");
        }
        else if(depositPanel.isEnabled()){
            depositTextField.setText(depositTextField.getText()+"0");
        }
        else if(setLimitPanel.isEnabled()){
            limitTextField.setText(limitTextField.getText()+"0");
        }
    }//GEN-LAST:event_b0ActionPerformed
    
    //Cancel button
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(withdrawPanel.isEnabled()){
            withdrawPanel.disable();
            withdrawPanel.setVisible(false);
            homePanel.enable();
            homePanel.setVisible(true);
        }
        else if(accountsPanel.isEnabled()){
            accountsPanel.disable();
            accountsPanel.setVisible(false);
            homePanel.enable();
            homePanel.setVisible(true);
        }
        else if(depositPanel.isEnabled()){
            depositPanel.disable();
            depositPanel.setVisible(false);
            homePanel.enable();
            homePanel.setVisible(true);
        }
        else if(balancePanel.isEnabled()){
            balancePanel.disable();
            balancePanel.setVisible(false);
            homePanel.enable();
            homePanel.setVisible(true);
            setLimitButton.disable();
            setLimitButton.setVisible(false);
        }
        else if(setLimitPanel.isEnabled()){
            setLimitPanel.disable();
            setLimitPanel.setVisible(false);
            balancePanel.enable();
            balancePanel.setVisible(true);
            limitTextField.setText("");
        }
        else{
            helpPanel.disable();
            helpPanel.setVisible(false);
            homePanel.enable();
            homePanel.setVisible(true);
        }            
        amountText.setText("");
        depositTextField.setText("");
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    //Savings button
    private void savingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsButtonActionPerformed
        tempAccount = "savings";
        transaction(savings);
        
    }//GEN-LAST:event_savingsButtonActionPerformed
    //Yes, continue button
    private void yesContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesContinueButtonActionPerformed
        continuePanel.disable();
        continuePanel.setVisible(false);
        homePanel.enable();
        homePanel.setVisible(true);
    }//GEN-LAST:event_yesContinueButtonActionPerformed
    //No, exit! button
    private void noExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noExitButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_noExitButtonActionPerformed
    //Cheque account button
    private void chequeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeButtonActionPerformed
        tempAccount = "cheque";
        transaction(cheque);        
    }//GEN-LAST:event_chequeButtonActionPerformed
    //Net Saver account button
    private void netButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netButtonActionPerformed
        tempAccount = "net";
        transaction(net);
        
    }//GEN-LAST:event_netButtonActionPerformed
    //Fixed account button
    private void fixedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedButtonActionPerformed
        tempAccount = "fixed";
        transaction(fixed);
        
    }//GEN-LAST:event_fixedButtonActionPerformed
    //Back from daily withdraw limit panel to balance panel
    private void backButtonD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonD1ActionPerformed
        limitTextField.setText("");
        setLimitPanel.disable();
        setLimitPanel.setVisible(false);
        balancePanel.enable();
        balancePanel.setVisible(true);
    }//GEN-LAST:event_backButtonD1ActionPerformed
    //Set limit button
    private void setLimitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLimitButtonActionPerformed
        balancePanel.disable();
        balancePanel.setVisible(false);
        setLimitPanel.enable();
        setLimitPanel.setVisible(true);
    }//GEN-LAST:event_setLimitButtonActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {          
                new ATM().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton $100Button;
    private javax.swing.JButton $200Button;
    private javax.swing.JButton $20Button;
    private javax.swing.JButton $50Button;
    private javax.swing.JLabel accDailyLimit;
    private javax.swing.JLabel accNameDisplay;
    private javax.swing.JLabel accNumberDisplay;
    private javax.swing.JLabel accTypeDisplay;
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JTextField amountText;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton backButtonB;
    private javax.swing.JButton backButtonD;
    private javax.swing.JButton backButtonD1;
    private javax.swing.JButton backButtonH;
    private javax.swing.JButton backButtonW;
    private javax.swing.JLabel background;
    private javax.swing.JButton balanceButton;
    private javax.swing.JLabel balanceDisplay;
    private javax.swing.JPanel balancePanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton chequeButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel continuePanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JTextField depositTextField;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton fixedButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField limitTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton netButton;
    private javax.swing.JButton noExitButton;
    private javax.swing.JButton savingsButton;
    private javax.swing.JButton setLimitButton;
    private javax.swing.JPanel setLimitPanel;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JPanel withdrawPanel;
    private javax.swing.JButton yesContinueButton;
    // End of variables declaration//GEN-END:variables
}
